### PR TITLE
PEER-226: Generative AI Assistance

### PR DESCRIPTION
**Pull request by anunayajoshi**
- good to re-review
- move openai to collab

### CODE REVIEW

**Comment by SeeuSim** [comment]
Please fix breaking builds

**Comment by SeeuSim** [comment]
image

User has to manually paste in the question and code. Please add the question and current code into context.

**Comment by SeeuSim** [comment]
Add streaming for interactivity, as well as error handling JIC the response takes too long

**Comment by SeeuSim** [comment]
BUG: chat clears on page refresh and I lose whatever chat I had with the LLM

**Comment by SeeuSim** [comment]
image


Updated styles for chat message

**Review by cyiting — APPROVED** [review]

**Pull request merged**
